-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 16:11:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boletim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boletim` DEFAULT CHARACTER SET utf8 ;
USE `boletim` ;

-- -----------------------------------------------------
-- Table `boletim`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Modalidade` (
  `idModalidade` INT NOT NULL,
  `identificadorModalidade` VARCHAR(45) NOT NULL,
  `tipoModalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModalidade`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Turma` (
  `idTurma` INT NOT NULL,
  `Modalidade_idModalidade` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `Modalidade_idModalidade`),
  INDEX `fk_Turma_Modalidade1_idx` (`Modalidade_idModalidade` ASC),
  CONSTRAINT `fk_Turma_Modalidade1`
    FOREIGN KEY (`Modalidade_idModalidade`)
    REFERENCES `boletim`.`Modalidade` (`idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Aluno` (
  `matriculaAluno` INT NOT NULL,
  `nomeAluno` VARCHAR(45) NOT NULL,
  `emailAluno` VARCHAR(45) NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  `Turma_Modalidade_idModalidade` INT NOT NULL,
  PRIMARY KEY (`matriculaAluno`, `Turma_idTurma`, `Turma_Modalidade_idModalidade`),
  INDEX `fk_Aluno_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Modalidade_idModalidade` ASC),
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Modalidade_idModalidade`)
    REFERENCES `boletim`.`Turma` (`idTurma` , `Modalidade_idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `nomeResponsavel` VARCHAR(45) NOT NULL,
  `emailResponsavel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idResponsavel`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Professor` (
  `idProfessor` INT NOT NULL,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  `emailProfessor` VARCHAR(45) NOT NULL,
  `titulacao` VARCHAR(45) NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Professor_idProfessor`),
  INDEX `fk_Professor_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `boletim`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nomeDisciplina` VARCHAR(45) NOT NULL,
  `cargaHoraria` INT NULL,
  `mediaParaPassar` FLOAT NOT NULL,
  PRIMARY KEY (`idDisciplina`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Conteudo` (
  `idConteudo` INT NOT NULL,
  `nomeConteudo` VARCHAR(45) NOT NULL,
  `cargaHorariaConteudo` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idConteudo`, `Disciplina_idDisciplina`),
  INDEX `fk_Conteudo_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  CONSTRAINT `fk_Conteudo_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `boletim`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Aluno_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Aluno_has_Disciplina` (
  `Aluno_matriculaAluno` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `notaAluno` FLOAT NULL,
  `faltasAluno` INT NOT NULL,
  PRIMARY KEY (`Aluno_matriculaAluno`, `Disciplina_idDisciplina`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` (`Aluno_matriculaAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_matriculaAluno`)
    REFERENCES `boletim`.`Aluno` (`matriculaAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `boletim`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Modalidade_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Modalidade_has_Disciplina` (
  `Modalidade_idModalidade` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Modalidade_idModalidade`, `Disciplina_idDisciplina`),
  INDEX `fk_Modalidade_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Modalidade_has_Disciplina_Modalidade1_idx` (`Modalidade_idModalidade` ASC),
  CONSTRAINT `fk_Modalidade_has_Disciplina_Modalidade1`
    FOREIGN KEY (`Modalidade_idModalidade`)
    REFERENCES `boletim`.`Modalidade` (`idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modalidade_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `boletim`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Professor_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Professor_has_Disciplina` (
  `Professor_idProfessor` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Disciplina_idDisciplina`),
  INDEX `fk_Professor_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Professor_has_Disciplina_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_has_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `boletim`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `boletim`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Turma_has_Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Turma_has_Professor` (
  `Turma_idTurma` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Professor_idProfessor`),
  INDEX `fk_Turma_has_Professor_Professor1_idx` (`Professor_idProfessor` ASC),
  INDEX `fk_Turma_has_Professor_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Professor_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `boletim`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `boletim`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


