-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 16:11:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boletim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boletim` DEFAULT CHARACTER SET utf8 ;
USE `boletim` ;

-- -----------------------------------------------------
-- Table `boletim`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Usuario` (
  `codigo` INT NOT NULL,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Modalidade` (
  `codigo` INT NOT NULL,
  `tipoModalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE = InnoDB;

INSERT INTO `boletim`.`Modalidade` (codigo, tipoModalidade) VALUES (0, "Ensino Fundamental 1");
INSERT INTO `boletim`.`Modalidade` (codigo, tipoModalidade) VALUES (1, "Ensino Fundamental 2");
INSERT INTO `boletim`.`Modalidade` (codigo, tipoModalidade) VALUES (2, "Ensino Médio");

-- -----------------------------------------------------
-- Table `boletim`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Turma` (
  `codigo` INT NOT NULL,
  `identificadorTurma` CHAR(2) NOT NULL,
  `Modalidade_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `Modalidade_codigo`),
  INDEX `fk_Turma_Modalidade1_idx` (`Modalidade_codigo` ASC),
  CONSTRAINT `fk_Turma_Modalidade1`
    FOREIGN KEY (`Modalidade_codigo`)
    REFERENCES `boletim`.`Modalidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Aluno` (
  `codigo` INT NOT NULL,
  `nomeAluno` VARCHAR(45) NOT NULL,
  `emailAluno` VARCHAR(45) NOT NULL,
  `Turma_codigo` INT NOT NULL,
  `Turma_Modalidade_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `Turma_codigo`, `Turma_Modalidade_codigo`),
  INDEX `fk_Aluno_Turma1_idx` (`Turma_codigo` ASC, `Turma_Modalidade_codigo` ASC),
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Turma_codigo` , `Turma_Modalidade_codigo`)
    REFERENCES `boletim`.`Turma` (`codigo` , `Modalidade_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Responsavel` (
  `codigo` INT NOT NULL,
  `nomeResponsavel` VARCHAR(45) NOT NULL,
  `emailResponsavel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Professor` (
  `codigo` INT NOT NULL,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  `emailProfessor` VARCHAR(45) NOT NULL,
  `titulacao` VARCHAR(45) NOT NULL,
  `Professor_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `Professor_codigo`),
  INDEX `fk_Professor_Professor1_idx` (`Professor_codigo` ASC),
  CONSTRAINT `fk_Professor_Professor1`
    FOREIGN KEY (`Professor_codigo`)
    REFERENCES `boletim`.`Professor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Disciplina` (
  `codigo` INT NOT NULL,
  `nomeDisciplina` VARCHAR(45) NOT NULL,
  `cargaHoraria` INT NULL,
  `mediaParaPassar` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Conteudo` (
  `codigo` INT NOT NULL,
  `nomeConteudo` VARCHAR(45) NOT NULL,
  `cargaHorariaConteudo` INT NOT NULL,
  `Disciplina_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `Disciplina_codigo`),
  INDEX `fk_Conteudo_Disciplina1_idx` (`Disciplina_codigo` ASC),
  CONSTRAINT `fk_Conteudo_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo`)
    REFERENCES `boletim`.`Disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Aluno_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Aluno_has_Disciplina` (
  `Aluno_codigo` INT NOT NULL,
  `Disciplina_codigo` INT NOT NULL,
  `notaAluno` FLOAT NULL,
  `faltasAluno` INT NOT NULL,
  PRIMARY KEY (`Aluno_codigo`, `Disciplina_codigo`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_codigo` ASC),
  INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` (`Aluno_codigo` ASC),
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_codigo`)
    REFERENCES `boletim`.`Aluno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo`)
    REFERENCES `boletim`.`Disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Modalidade_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Modalidade_has_Disciplina` (
  `Modalidade_codigo` INT NOT NULL,
  `Disciplina_codigo` INT NOT NULL,
  PRIMARY KEY (`Modalidade_codigo`, `Disciplina_codigo`),
  INDEX `fk_Modalidade_has_Disciplina_Disciplina1_idx` (`Disciplina_codigo` ASC),
  INDEX `fk_Modalidade_has_Disciplina_Modalidade1_idx` (`Modalidade_codigo` ASC),
  CONSTRAINT `fk_Modalidade_has_Disciplina_Modalidade1`
    FOREIGN KEY (`Modalidade_codigo`)
    REFERENCES `boletim`.`Modalidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modalidade_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo`)
    REFERENCES `boletim`.`Disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Professor_has_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Professor_has_Disciplina` (
  `Professor_codigo` INT NOT NULL,
  `Disciplina_codigo` INT NOT NULL,
  PRIMARY KEY (`Professor_codigo`, `Disciplina_codigo`),
  INDEX `fk_Professor_has_Disciplina_Disciplina1_idx` (`Disciplina_codigo` ASC),
  INDEX `fk_Professor_has_Disciplina_Professor1_idx` (`Professor_codigo` ASC),
  CONSTRAINT `fk_Professor_has_Disciplina_Professor1`
    FOREIGN KEY (`Professor_codigo`)
    REFERENCES `boletim`.`Professor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo`)
    REFERENCES `boletim`.`Disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `boletim`.`Turma_has_Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boletim`.`Turma_has_Professor` (
  `Turma_codigo` INT NOT NULL,
  `Professor_codigo` INT NOT NULL,
  PRIMARY KEY (`Turma_codigo`, `Professor_codigo`),
  INDEX `fk_Turma_has_Professor_Professor1_idx` (`Professor_codigo` ASC),
  INDEX `fk_Turma_has_Professor_Turma1_idx` (`Turma_codigo` ASC),
  CONSTRAINT `fk_Turma_has_Professor_Turma1`
    FOREIGN KEY (`Turma_codigo`)
    REFERENCES `boletim`.`Turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_Professor1`
    FOREIGN KEY (`Professor_codigo`)
    REFERENCES `boletim`.`Professor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;